NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.gc.goodchar.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.gc.goodchar.com-cert.pem
    OrganizationalUnitIdentifier: peer
